apiVersion: v1
kind: Namespace
metadata:
  name: test-rsync
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc-request
  namespace: test-rsync
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-container
  namespace: test-rsync
  labels:
    app: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
        - name: ubuntu
          image: ubuntu
          command:
            - bin/bash
          args:
            - -c
            - sleep 1000
          volumeMounts:
            - mountPath: /test_shared
              name: shared
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: test-pvc-request
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-container-sqlite3
  namespace: test-rsync
  labels:
    app: sqlite3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlite3
  template:
    metadata:
      labels:
        app: sqlite3
    spec:
      containers:
        - name: sqlite3
          image: ubuntu
          command:
            - bin/bash
          args:
            - -c
            - "touch /test_sqlite3/esempio.sqlite3 && trap : TERM INT; sleep infinity & wait"
          volumeMounts:
            - mountPath: /test_sqlite3
              name: shared
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: test-pvc-request-sqlite3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc-request-sqlite3
  namespace: test-rsync
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi