version: '3.8'

services:

  db:
    image: mysql
    environment:
      MYSQL_DATABASE: world
      MYSQL_USER_FILE: '/esempio_file_mysql_username'
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: root
    configs:
      - source: mysql_username
        target: /esempio_file_mysql_username
    volumes:
      - ./world.sql.gz:/docker-entrypoint-initdb.d/world.sql.gz

  db_pg:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mio_db


  second:
    image: wordpress
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./cartella_bindata:/test_bind

  test_sqlite3:
    image: ubuntu
    command: '/bin/bash -c "touch /cartella_sqlite3/esempio.sqlite3 && trap : TERM INT; sleep infinity & wait"'
    volumes:
      - sqlite:/cartella_sqlite3

  mongo:
    image: mongo:4.2

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081

volumes:
  sqlite:

configs:
  mysql_username:
    file: ./mysql_username

